version: '3.8'

services:
  proxy:
    container_name: blendbrain_proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: blendbrain_server
    build:
      context: ./
      dockerfile: dockerfile.node
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    restart: "unless-stopped"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  node_modules:
